sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
language: scala
scala:
- 2.12.6
jdk:
- oraclejdk8

script:
- ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publishSigned;
  fi
after_success:
- ./sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
notifications:
  email:
  - on_success: "always"

